In [1]:
## import pandas 
import pandas as pd

In [2]:
## import data
taxi_df= pd.read_csv("311-data.csv")

In [3]:
taxi_df.head(20)

,Unique Key,Created Date,Closed Date,Agency,Agency Name,Problem (formerly Complaint Type),Problem Detail (formerly Descriptor),Additional Details,Location Type,Incident Zip,...,Vehicle Type,Taxi Company Borough,Taxi Pick Up Location,Bridge Highway Name,Bridge Highway Direction,Road Ramp,Bridge Highway Segment,Latitude,Longitude,Location
0,67345192,12/31/2025 11:58:25 PM,01/02/2026 11:55:46 AM,TLC,Taxi and Limousine Commission,Lost Property,Bag/Wallet,Purse,Taxi,10011.0,...,NaN,NaN,"120 5 AVENUE, MANHATTAN (NEW YORK), NY, 10011",NaN,NaN,NaN,NaN,40.738077,-73.992123,POINT (-73.992122616114 40.738076887271)
1,67348740,12/31/2025 11:20:23 PM,01/02/2026 01:27:51 PM,TLC,Taxi and Limousine Commission,Lost Property,Bag/Wallet,Backpack,Taxi,11430.0,...,NaN,NaN,"JOHN F KENNEDY AIRPORT, QUEENS (JAMAICA) ,NY, ...",NaN,NaN,NaN,NaN,40.648320,-73.788281,POINT (-73.788281251302 40.648320486201)
2,67349981,12/31/2025 11:05:23 PM,NaN,TLC,Taxi and Limousine Commission,For Hire Vehicle Complaint,Driver Complaint - Passenger,Discourteous,Street,11435.0,...,NaN,NaN,"148-25 89 AVENUE, QUEENS (JAMAICA), NY, 11435",NaN,NaN,NaN,NaN,40.704243,-73.807266,POINT (-73.807265995267 40.704243098808)
3,67348745,12/31/2025 10:50:29 PM,NaN,TLC,Taxi and Limousine Commission,Taxi Complaint,Driver Complaint - Passenger,Fare/Tip Complaint,Street,11430.0,...,NaN,NaN,"JOHN F KENNEDY AIRPORT, QUEENS (JAMAICA) ,NY, ...",NaN,NaN,NaN,NaN,40.648320,-73.788281,POINT (-73.788281251302 40.648320486201)
4,67348746,12/31/2025 10:42:43 PM,NaN,TLC,Taxi and Limousine Commission,Taxi Complaint,Driver Complaint - Passenger,Fare/Tip Complaint,Street,11369.0,...,NaN,NaN,"LA GUARDIA AIRPORT, QUEENS (EAST ELMHURST) ,NY...",NaN,NaN,NaN,NaN,40.774421,-73.877294,POINT (-73.877294105139 40.774420865988)
5,67353556,12/31/2025 08:13:18 PM,NaN,TLC,Taxi and Limousine Commission,For Hire Vehicle Complaint,Driver Complaint - Passenger,Fare/Tip/Receipt,Street,11369.0,...,NaN,QUEENS,"LA GUARDIA AIRPORT, QUEENS (EAST ELMHURST) ,NY...",NaN,NaN,NaN,NaN,40.774421,-73.877294,POINT (-73.877294105139 40.774420865988)
6,67347653,12/31/2025 08:10:17 PM,NaN,TLC,Taxi and Limousine Commission,For Hire Vehicle Complaint,Driver Complaint - Non Passenger,Unsafe Driving,Street,10007.0,...,NaN,NaN,"22 DEY STREET, MANHATTAN (NEW YORK), NY, 10007",NaN,NaN,NaN,NaN,40.710835,-74.010381,POINT (-74.010381056064 40.710834971)
7,67351142,12/31/2025 08:03:06 PM,NaN,TLC,Taxi and Limousine Commission,Taxi Complaint,Driver Complaint - Passenger,Fare/Tip Complaint,Street,11430.0,...,NaN,NaN,"JOHN F KENNEDY AIRPORT, QUEENS (JAMAICA) ,NY, ...",NaN,NaN,NaN,NaN,40.648320,-73.788281,POINT (-73.788281251302 40.648320486201)
8,67348747,12/31/2025 07:47:22 PM,NaN,TLC,Taxi and Limousine Commission,Taxi Complaint,Driver Complaint - Passenger,Unsafe Driving - Passenger,Street,11369.0,...,NaN,NaN,"LA GUARDIA AIRPORT, QUEENS (EAST ELMHURST) ,NY...",NaN,NaN,NaN,NaN,40.774421,-73.877294,POINT (-73.877294105139 40.774420865988)
9,67346486,12/31/2025 07:22:44 PM,NaN,TLC,Taxi and Limousine Commission,Taxi Complaint,Driver Complaint - Non Passenger,Unauthorized Pick-Up Location,Street,10001.0,...,NaN,NaN,"455 8 AVENUE, MANHATTAN (NEW YORK), NY, 10001",NaN,NaN,NaN,NaN,40.751389,-73.994059,POINT (-73.994059200662 40.751389039705)
10,67350060,12/31/2025 07:02:49 PM,01/23/2026 09:19:26 AM,TLC,Taxi and Limousine Commission,For Hire Vehicle Complaint,Driver Complaint - Non Passenger,Unsafe Driving,Street,10475.0,...,NaN,BRONX,"BAY PLAZA, BRONX ,NY, 10475",NaN,NaN,NaN,NaN,40.868908,-73.825894,POINT (-73.825893678807 40.868907608336)
11,67348869,12/31/2025 06:43:52 PM,01/23/2026 09:18:23 AM,TLC,Taxi and Limousine Commission,For Hire Vehicle Complaint,Driver Complaint - Non Passenger,Unsafe Driving,Street,11216.0,...,NaN,NaN,"1160 FULTON STREET, BROOKLYN, NY, 11216",NaN,NaN,NaN,NaN,40.680906,-73.954658,POINT (-73.954658243732 40.680905792303)
12,67351258,12/31/2025 06:23:30 PM,NaN,TLC,Taxi and Limousine Commission,For Hire Vehicle Complaint,Driver Complaint - Non Passenger,Unsafe Driving,Street,10036.0,...,NaN,NaN,"570 11 AVENUE, MANHATTAN (NEW YORK), NY, 10036",NaN,NaN,NaN,NaN,40.761397,-73.997885,POINT (-73.997884671036 40.761396514271)
13,67353557,12/31/2025 05:47:17 PM,NaN,TLC,Taxi and Limousine Commission,For Hire Vehicle Complaint,Driver Complaint - Passenger,Unsafe Driving,Street,10022.0,...,NaN,NaN,"EAST 54 STREET AND LEXINGTON AVENUE, MANHATT...",NaN,NaN,NaN,NaN,40.758999,-73.970534,POINT (-73.970534455264 40.758999348952)
14,67350063,12/31/2025 05:30:02 PM,01/23/2026 09:17:05 AM,TLC,Taxi and Limousine Commission,For Hire Vehicle Complaint,Driver Complaint - Non Passenger,Unsafe Driving,Street,10003.0,...,NaN,NaN,"21 EAST 8 STREET, MANHATTAN (NEW YORK), NY,...",NaN,NaN,NaN,NaN,40.731778,-73.995201,POINT (-73.995201131388 40.731777847362)
15,67353529,12/31/2025 05:03:59 PM,NaN,TLC,Taxi and Limousine Commission,Taxi Complaint,Driver Complaint - Passenger,Fare/Tip Complaint - Credit Card,Street,11430.0,...,NaN,NaN,"JOHN F KENNEDY AIRPORT, QUEENS (JAMAICA) ,NY, ...",NaN,NaN,NaN,NaN,40.648320,-73.788281,POINT (-73.788281251302 40.648320486201)
16,67348868,12/31/2025 04:36:53 PM,NaN,TLC,Taxi and Limousine Commission,For Hire Vehicle Complaint,Driver Complaint - Non Passenger,Unsafe Driving,Street,11414.0,...,NaN,NaN,"53 BROADWAY, QUEENS (HOWARD BEACH), NY, 11414",NaN,NaN,NaN,NaN,40.657329,-73.829888,POINT (-73.829887844518 40.657329326174)
17,67347639,12/31/2025 04:35:12 PM,01/06/2026 09:17:02 AM,TLC,Taxi and Limousine Commission,Taxi Compliment,Driver Compliment,Above and Beyond to Help,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,67352321,12/31/2025 04:24:49 PM,NaN,TLC,Taxi and Limousine Commission,For Hire Vehicle Complaint,Driver Complaint - Passenger,Denied Request,Street,10028.0,...,NaN,MANHATTAN,"203 EAST 86 STREET, MANHATTAN (NEW YORK), NY...",NaN,NaN,NaN,NaN,40.778698,-73.953675,POINT (-73.953674533077 40.778698294727)
19,67345180,12/31/2025 04:14:00 PM,NaN,TLC,Taxi and Limousine Commission,For Hire Vehicle Complaint,Driver Complaint - Passenger,License Not Displayed,Street,10462.0,...,NaN,BRONX,"2111 STARLING AVENUE, BRONX, NY, 10462",NaN,NaN,NaN,NaN,40.836099,-73.854753,POINT (-73.854752896596 40.836098893609)

In [4]:
## sampling data

taxi_df.sample(10)

,Unique Key,Created Date,Closed Date,Agency,Agency Name,Problem (formerly Complaint Type),Problem Detail (formerly Descriptor),Additional Details,Location Type,Incident Zip,...,Vehicle Type,Taxi Company Borough,Taxi Pick Up Location,Bridge Highway Name,Bridge Highway Direction,Road Ramp,Bridge Highway Segment,Latitude,Longitude,Location
29982,64330545,03/12/2025 04:36:15 PM,04/24/2025 08:32:07 AM,TLC,Taxi and Limousine Commission,For Hire Vehicle Complaint,Driver Complaint - Non Passenger,Unsafe Driving,Street,11430.0,...,NaN,QUEENS,"JOHN F KENNEDY AIRPORT, QUEENS (JAMAICA) ,NY, ...",NaN,NaN,NaN,NaN,40.648320,-73.788281,POINT (-73.788281251302 40.648320486201)
21804,65171960,06/05/2025 08:40:25 AM,02/25/2026 02:15:11 PM,TLC,Taxi and Limousine Commission,Taxi Complaint,Driver Complaint - Non Passenger,Unsafe Driving - Non-Passenger,Highway,NaN,...,NaN,NaN,NaN,Jackie Robinson/Interboro Pkwy,Westbound,Roadway,Cypress Ave Vermont Place (Exit 2) - Bushwick ...,NaN,NaN,NaN
21935,65155195,06/03/2025 09:45:52 PM,12/15/2025 05:22:21 PM,TLC,Taxi and Limousine Commission,For Hire Vehicle Complaint,Driver Complaint - Non Passenger,Unsafe Driving,Street,10017.0,...,NaN,NaN,"750 1 AVENUE, MANHATTAN (NEW YORK), NY, 10017",NaN,NaN,NaN,NaN,40.748981,-73.969698,POINT (-73.969697965314 40.748980808102)
28876,64463149,03/25/2025 01:48:51 PM,07/11/2025 04:29:53 PM,TLC,Taxi and Limousine Commission,For Hire Vehicle Complaint,Driver Complaint - Non Passenger,Unsafe Driving,Street,10012.0,...,NaN,NaN,"18 EAST HOUSTON STREET, MANHATTAN (NEW YORK), ...",NaN,NaN,NaN,NaN,40.725281,-73.996111,POINT (-73.996110769894 40.725281044357)
1797,67151873,12/12/2025 11:07:46 AM,01/16/2026 10:08:16 AM,TLC,Taxi and Limousine Commission,Taxi Complaint,Driver Complaint - Passenger,Fare/Tip Complaint,Street,10022.0,...,NaN,NaN,"687 LEXINGTON AVENUE, MANHATTAN (NEW YORK), NY...",NaN,NaN,NaN,NaN,40.760564,-73.969386,POINT (-73.969385868685 40.760563553499)
2067,67116238,12/09/2025 04:19:45 PM,NaN,TLC,Taxi and Limousine Commission,For Hire Vehicle Complaint,Driver Complaint - Non Passenger,Unsafe Driving,Street,10011.0,...,NaN,NaN,"60 WEST 20 STREET, MANHATTAN (NEW YORK), NY,...",NaN,NaN,NaN,NaN,40.740443,-73.992794,POINT (-73.992793543632 40.740442907321)
9655,66369308,10/04/2025 03:29:20 PM,NaN,TLC,Taxi and Limousine Commission,For Hire Vehicle Complaint,Driver Complaint - Non Passenger,Unsafe Driving,Street,10002.0,...,NaN,NaN,"183 EAST HOUSTON STREET, MANHATTAN (NEW YORK),...",NaN,NaN,NaN,NaN,40.722739,-73.988026,POINT (-73.988026101706 40.722738841849)
18334,65533337,07/11/2025 02:32:54 PM,07/15/2025 08:24:46 AM,TLC,Taxi and Limousine Commission,Lost Property,Other,Keys,Taxi,10016.0,...,NaN,NaN,"2 AVENUE AND EAST 38 STREET, MANHATTAN, NY, ...",NaN,NaN,NaN,NaN,40.747297,-73.974044,POINT (-73.974043982518 40.747296593855)
15551,65807610,08/09/2025 01:44:05 PM,09/04/2025 02:16:17 PM,TLC,Taxi and Limousine Commission,For Hire Vehicle Complaint,Driver Complaint - Non Passenger,Unsafe Driving,NaN,11210.0,...,NaN,NaN,"BEDFORD AVENUE AND FARRAGUT ROAD, BROOKLYN, NY...",NaN,NaN,NaN,NaN,40.635817,-73.953424,POINT (-73.953424232503 40.635816788732)
11396,66192464,09/18/2025 07:43:34 PM,10/28/2025 08:20:22 AM,TLC,Taxi and Limousine Commission,Taxi Complaint,Driver Complaint - Non Passenger,Unsafe Driving - Non-Passenger,Street,11377.0,...,NaN,NaN,"26-46 BROOKLYN QUEENS EXPRESSWAY, QUEENS (WOOD...",NaN,NaN,NaN,NaN,40.761712,-73.902164,POINT (-73.902163747085 40.761711807224)

In [5]:
## gauging complaints
## that's annoying that fare/tip is different ; I'm also curious about contract dispute

taxi_df["Additional Details"].unique()

<StringArray>
[                           'Purse',                         'Backpack',
                     'Discourteous',               'Fare/Tip Complaint',
                 'Fare/Tip/Receipt',                   'Unsafe Driving',
       'Unsafe Driving - Passenger',    'Unauthorized Pick-Up Location',
 'Fare/Tip Complaint - Credit Card',         'Above and Beyond to Help',
                   'Denied Request',            'License Not Displayed',
                     'Shopping Bag',                            'Other',
                          'Earring',                         'Tote Bag',
   'Unsafe Driving - Non-Passenger',                          'Glasses',
                  'Route Complaint',                       'Cell Phone',
                  'Refused Pick-Up',           'Unclean Condition/Odor',
    'Refusal to Accept Credit Card',          'Unlicensed/Unauthorized',
                             'Keys',                         'Suitcase',
                              'Hat',                           'Wallet',
                           'Camera',                  'Computer/Laptop',
            'Service Delay/No Show',    'Returned Passenger's Property',
                        'Briefcase',                           'Gloves',
                   'Cell Phone Use',                           'Jacket',
   'Cell Phone Use - Non-Passenger',                            'Watch',
                         'Necklace',                             'Coat',
                 'Combined Pickups',         'Broken/Missing Equipment',
                           'Guitar',            'Courteous/Kind/Polite',
                            'Scarf',   'Unauthorized Vehicle Operation',
                         'Passport',                             'Ring',
                              'Toy',                            'Shoes',
                       'Money Clip',     'Broken Card Reader or Screen',
                   'Broken/Missing',                         'Stroller',
                 'Drop-Off Refused',                  'Binder/Notebook',
                         'Umbrella',            'Reward/Tip Submission',
   'Passenger Without Enough Funds',                          'Racquet',
                         'Envelope',                            'Pager',
           'Handheld Organizer/PDA',    'Discourteous/Harassment/Abuse',
                 'Contract Dispute',                          'Planner',
                  'MP3 Player/iPod',                         'Document',
                         'Bracelet',                             'Book',
                             'Ball',                              'Box',
                   'Religious Item',                                nan,
                                '1',                           'Folder',
                              'Bat',                        'Saxophone',
                         'Keyboard']
Length: 79, dtype: str

In [45]:
unauthorized=taxi_df[taxi_df["Additional Details"] == 'Unauthorized Vehicle Operation']
unauthorized.count()

Unique Key                              5
Created Date                            5
Closed Date                             1
Agency                                  5
Agency Name                             5
Problem (formerly Complaint Type)       5
Problem Detail (formerly Descriptor)    5
Additional Details                      5
Location Type                           0
Incident Zip                            4
Incident Address                        4
Street Name                             4
Cross Street 1                          4
Cross Street 2                          4
Intersection Street 1                   4
Intersection Street 2                   4
Address Type                            4
City                                    2
Landmark                                2
Facility Type                           0
Status                                  5
Due Date                                0
Resolution Description                  1
Resolution Action Updated Date          1
Community Board                         5
Council District                        4
Police Precinct                         5
BBL                                     2
Borough                                 5
X Coordinate (State Plane)              4
Y Coordinate (State Plane)              4
Open Data Channel Type                  5
Park Facility Name                      5
Park Borough                            5
Vehicle Type                            0
Taxi Company Borough                    0
Taxi Pick Up Location                   4
Bridge Highway Name                     0
Bridge Highway Direction                0
Road Ramp                               0
Bridge Highway Segment                  0
Latitude                                4
Longitude                               4
Location                                4
dtype: int64

In [48]:
## looking for complaints of unlicensed drivers, creating a df 
unlicensed_complaint=taxi_df[taxi_df["Additional Details"] == 'Unlicensed/Unauthorized']
(unlicensed_complaint).count()

## there are 274 complaints of unlicensed cabs , not including the 5 "unauthorized"

Unique Key                              274
Created Date                            274
Closed Date                             147
Agency                                  274
Agency Name                             274
Problem (formerly Complaint Type)       274
Problem Detail (formerly Descriptor)    274
Additional Details                      274
Location Type                           231
Incident Zip                            262
Incident Address                        263
Street Name                             263
Cross Street 1                          261
Cross Street 2                          263
Intersection Street 1                   261
Intersection Street 2                   263
Address Type                            263
City                                    242
Landmark                                242
Facility Type                             0
Status                                  274
Due Date                                  0
Resolution Description                  147
Resolution Action Updated Date          147
Community Board                         274
Council District                        263
Police Precinct                         274
BBL                                     216
Borough                                 274
X Coordinate (State Plane)              263
Y Coordinate (State Plane)              263
Open Data Channel Type                  274
Park Facility Name                      274
Park Borough                            274
Vehicle Type                            234
Taxi Company Borough                    126
Taxi Pick Up Location                   263
Bridge Highway Name                       5
Bridge Highway Direction                  5
Road Ramp                                 5
Bridge Highway Segment                    5
Latitude                                263
Longitude                               263
Location                                263
dtype: int64

In [35]:
pd.set_option('display.max_colwidth', None)

In [38]:
##searching for incidents at JFK
complaint_jfk=unlicensed_complaint.query("`Incident Zip` == 11430.0")
complaint_jfk

,Unique Key,Created Date,Closed Date,Agency,Agency Name,Problem (formerly Complaint Type),Problem Detail (formerly Descriptor),Additional Details,Location Type,Incident Zip,Incident Address,Street Name,Cross Street 1,Cross Street 2,Intersection Street 1,Intersection Street 2,Address Type,City,Landmark,Facility Type,Status,Due Date,Resolution Description,Resolution Action Updated Date,Community Board,Council District,Police Precinct,BBL,Borough,X Coordinate (State Plane),Y Coordinate (State Plane),Open Data Channel Type,Park Facility Name,Park Borough,Vehicle Type,Taxi Company Borough,Taxi Pick Up Location,Bridge Highway Name,Bridge Highway Direction,Road Ramp,Bridge Highway Segment,Latitude,Longitude,Location
70,67335775,12/30/2025 10:52:55 PM,NaN,TLC,Taxi and Limousine Commission,For Hire Vehicle Complaint,Car Service Company Complaint,Unlicensed/Unauthorized,Street,11430.0,JOHN F KENNEDY AIRPORT,JOHN F KENNEDY AIRPORT,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,PLACE,JAMAICA,JOHN F KENNEDY AIRPORT,NaN,In Progress,NaN,NaN,NaN,83 QUEENS,31.0,Precinct 113,4.142600e+09,QUEENS,"1,043,001","175,548",ONLINE,Unspecified,QUEENS,Car Service,NaN,"JOHN F KENNEDY AIRPORT, QUEENS (JAMAICA) ,NY, 11430",NaN,NaN,NaN,NaN,40.64832,-73.788281,POINT (-73.788281251302 40.648320486201)
173,67329354,12/29/2025 05:40:14 PM,03/11/2026 02:44:36 PM,TLC,Taxi and Limousine Commission,For Hire Vehicle Complaint,Car Service Company Complaint,Unlicensed/Unauthorized,Street,11430.0,JOHN F KENNEDY AIRPORT,JOHN F KENNEDY AIRPORT,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,PLACE,JAMAICA,JOHN F KENNEDY AIRPORT,NaN,Closed,NaN,"Based on the information provided by the customer, the Taxi and Limousine Commission has determined that a hearing is not necessary or not possible.",03/11/2026 02:44:40 PM,83 QUEENS,31.0,Precinct 113,4.142600e+09,QUEENS,"1,043,001","175,548",ONLINE,Unspecified,QUEENS,Car Service,QUEENS,"JOHN F KENNEDY AIRPORT, QUEENS (JAMAICA) ,NY, 11430",NaN,NaN,NaN,NaN,40.64832,-73.788281,POINT (-73.788281251302 40.648320486201)
568,67277487,12/23/2025 12:04:21 PM,03/11/2026 02:35:00 PM,TLC,Taxi and Limousine Commission,For Hire Vehicle Complaint,Car Service Company Complaint,Unlicensed/Unauthorized,Street,11430.0,JOHN F KENNEDY AIRPORT,JOHN F KENNEDY AIRPORT,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,PLACE,JAMAICA,JOHN F KENNEDY AIRPORT,NaN,Closed,NaN,"Based on the information provided by the customer, the Taxi and Limousine Commission has determined that a hearing is not necessary or not possible.",03/11/2026 02:35:02 PM,83 QUEENS,31.0,Precinct 113,4.142600e+09,QUEENS,"1,043,001","175,548",PHONE,Unspecified,QUEENS,Car Service,QUEENS,"JOHN F KENNEDY AIRPORT, QUEENS (JAMAICA) ,NY, 11430",NaN,NaN,NaN,NaN,40.64832,-73.788281,POINT (-73.788281251302 40.648320486201)
616,67273967,12/22/2025 07:27:58 PM,NaN,TLC,Taxi and Limousine Commission,For Hire Vehicle Complaint,Car Service Company Complaint,Unlicensed/Unauthorized,Highway,11430.0,JOHN F KENNEDY AIRPORT,JOHN F KENNEDY AIRPORT,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,PLACE,JAMAICA,JOHN F KENNEDY AIRPORT,NaN,In Progress,NaN,NaN,NaN,83 QUEENS,31.0,Precinct 113,4.142600e+09,QUEENS,"1,043,001","175,548",ONLINE,Unspecified,QUEENS,Car Service,NaN,"JOHN F KENNEDY AIRPORT, QUEENS (JAMAICA) ,NY, 11430",Van Wyck Expwy,North/Bronx Bound,Ramp,Jamaica Ave Hillside Ave (Exit 6),40.64832,-73.788281,POINT (-73.788281251302 40.648320486201)
774,67254238,12/20/2025 08:24:14 PM,NaN,TLC,Taxi and Limousine Commission,For Hire Vehicle Report,Car Service Company Report,Unlicensed/Unauthorized,NaN,11430.0,JOHN F KENNEDY AIRPORT,JOHN F KENNEDY AIRPORT,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,PLACE,JAMAICA,JOHN F KENNEDY AIRPORT,NaN,In Progress,NaN,NaN,NaN,83 QUEENS,31.0,Precinct 113,4.142600e+09,QUEENS,"1,043,001","175,548",ONLINE,Unspecified,QUEENS,NaN,NaN,"JOHN F KENNEDY AIRPORT, QUEENS (JAMAICA) ,NY, 11430",NaN,NaN,NaN,NaN,40.64832,-73.788281,POINT (-73.788281251302 40.648320486201)
1445,67199698,12/15/2025 05:05:42 AM,NaN,TLC,Taxi and Limousine Commission,For Hire Vehicle Report,Car Service Company Report,Unlicensed/Unauthorized,NaN,11430.0,JOHN F KENNEDY AIRPORT,JOHN F KENNEDY AIRPORT,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,PLACE,JAMAICA,JOHN F KENNEDY AIRPORT,NaN,In Progress,NaN,NaN,NaN,83 QUEENS,31.0,Precinct 113,4.142600e+09,QUEENS,"1,043,001","175,548",ONLINE,Unspecified,QUEENS,NaN,NaN,"JOHN F KENNEDY AIRPORT, QUEENS (JAMAICA) ,NY, 11430",NaN,NaN,NaN,NaN,40.64832,-73.788281,POINT (-73.788281251302 40.648320486201)
2254,67089128,12/07/2025 11:25:30 PM,NaN,TLC,Taxi and Limousine Commission,For Hire Vehicle Report,Car Service Company Report,Unlicensed/Unauthorized,NaN,11430.0,JOHN F KENNEDY AIRPORT,JOHN F KENNEDY AIRPORT,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,PLACE,JAMAICA,JOHN F KENNEDY AIRPORT,NaN,In Progress,NaN,NaN,NaN,83 QUEENS,31.0,Precinct 113,4.142600e+09,QUEENS,"1,043,001","175,548",PHONE,Unspecified,QUEENS,NaN,NaN,"JOHN F KENNEDY AIRPORT, QUEENS (JAMAICA) ,NY, 11430",NaN,NaN,NaN,NaN,40.64832,-73.788281,POINT (-73.788281251302 40.648320486201)
2998,67012871,12/01/2025 10:05:41 PM,NaN,TLC,Taxi and Limousine Commission,For Hire Vehicle Complaint,Car Service Company Complaint,Unlicensed/Unauthorized,Street,11430.0,JOHN F KENNEDY AIRPORT,JOHN F KENNEDY AIRPORT,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,PLACE,JAMAICA,JOHN F KENNEDY AIRPORT,NaN,In Progress,NaN,NaN,NaN,83 QUEENS,31.0,Precinct 113,4.142600e+09,QUEENS,"1,043,001","175,548",ONLINE,Unspecified,QUEENS,Car Service,MANHATTAN,"JOHN F KENNEDY AIRPORT, QUEENS (JAMAICA) ,NY, 11430",NaN,NaN,NaN,NaN,40.64832,-73.788281,POINT (-73.788281251302 40.648320486201)
3085,67001665,12/01/2025 12:10:04 AM,NaN,TLC,Taxi and Limousine Commission,For Hire Vehicle Complaint,Car Service Company Complaint,Unlicensed/Unauthorized,Street,11430.0,JOHN F KENNEDY AIRPORT,JOHN F KENNEDY AIRPORT,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,PLACE,JAMAICA,JOHN F KENNEDY AIRPORT,NaN,In Progress,NaN,NaN,NaN,83 QUEENS,31.0,Precinct 113,4.142600e+09,QUEENS,"1,043,001","175,548",ONLINE,Unspecified,QUEENS,Car Service,QUEENS,"JOHN F KENNEDY AIRPORT, QUEENS (JAMAICA) ,NY, 11430",NaN,NaN,NaN,NaN,40.64832,-73.788281,POINT (-73.788281251302 40.648320486201)
3484,66953982,11/25/2025 11:06:30 PM,NaN,TLC,Taxi and Limousine Commission,For Hire Vehicle Report,Car Service Company Report,Unlicensed/Unauthorized,NaN,11430.0,JOHN F KENNEDY AIRPORT,JOHN F KENNEDY AIRPORT,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,PLACE,JAMAICA,JOHN F KENNEDY AIRPORT,NaN,In Progress,NaN,NaN,NaN,83 QUEENS,31.0,Precinct 113,4.142600e+09,QUEENS,"1,043,001","175,548",ONLINE,Unspecified,QUEENS,NaN,NaN,"JOHN F KENNEDY AIRPORT, QUEENS (JAMAICA) ,NY, 11430",NaN,NaN,NaN,NaN,40.64832,-73.788281,POINT (-73.788281251302 40.648320486201)
3647,66940679,11/24/2025 01:49:37 PM,NaN,TLC,Taxi and Limousine Commission,For Hire Vehicle Complaint,Car Service Company Complaint,Unlicensed/Unauthorized,Street,11430.0,JOHN F KENNEDY AIRPORT,JOHN F KENNEDY AIRPORT,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,PLACE,JAMAICA,JOHN F KENNEDY AIRPORT,NaN,In Progress,NaN,NaN,NaN,83 QUEENS,31.0,Precinct 113,4.142600e+09,QUEENS,"1,043,001","175,548",PHONE,Unspecified,QUEENS,Car Service,QUEENS,"JOHN F KENNEDY AIRPORT, QUEENS (JAMAICA) ,NY, 11430",NaN,NaN,NaN,NaN,40.64832,-73.788281,POINT (-73.788281251302 40.648320486201)
5020,66815666,11/12/2025 09:12:02 AM,NaN,TLC,Taxi and Limousine Commission,For Hire Vehicle Complaint,Car Service Company Complaint,Unlicensed/Unauthorized,Street,11430.0,JOHN F KENNEDY AIRPORT,JOHN F KENNEDY AIRPORT,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,PLACE,JAMAICA,JOHN F KENNEDY AIRPORT,NaN,In Progress,NaN,NaN,NaN,83 QUEENS,31.0,Precinct 113,4.142600e+09,QUEENS,"1,043,001","175,548",ONLINE,Unspecified,QUEENS,Car Service,NaN,"JOHN F KENNEDY AIRPORT, QUEENS (JAMAICA) ,NY, 11430",NaN,NaN,NaN,NaN,40.64832,-73.788281,POINT (-73.788281251302 40.648320486201)
5034,66817439,11/12/2025 07:51:58 AM,NaN,TLC,Taxi and Limousine Commission,For Hire Vehicle Complaint,Car Service Company Complaint,Unlicensed/Unauthorized,Street,11430.0,JOHN F KENNEDY AIRPORT,JOHN F KENNEDY AIRPORT,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,PLACE,JAMAICA,JOHN F KENNEDY AIRPORT,NaN,In Progress,NaN,NaN,NaN,83 QUEENS,31.0,Precinct 113,4.142600e+09,QUEENS,"1,043,001","175,548",ONLINE,Unspecified,QUEENS,Car Service,BROOKLYN,"JOHN F KENNEDY AIRPORT, QUEENS (JAMAICA) ,NY, 11430",NaN,NaN,NaN,NaN,40.64832,-73.788281,POINT (-73.788281251302 40.648320486201)
5279,66778128,11/10/2025 12:50:49 AM,03/11/2026 10:07:04 AM,TLC,Taxi and Limousine Commission,For Hire Vehicle Complaint,Car Service Company Complaint,Unlicensed/Unauthorized,Street,11430.0,JOHN F KENNEDY AIRPORT,JOHN F KENNEDY AIRPORT,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,PLACE,JAMAICA,JOHN F KENNEDY AIRPORT,NaN,Closed,NaN,"Based on the information provided by the customer, the Taxi and Limousine Commission has determined that a hearing is not necessary or not possible.",03/11/2026 10:07:06 AM,83 QUEENS,31.0,Precinct 113,4.142600e+09,QUEENS,"1,043,001","175,548",ONLINE,Unspecified,QUEENS,Car Service,NaN,"JOHN F KENNEDY AIRPORT, QUEENS (JAMAICA) ,NY, 11430",NaN,NaN,NaN,NaN,40.64832,-73.788281,POINT (-73.788281251302 40.648320486201)
6079,66690152,11/01/2025 10:01:14 PM,NaN,TLC,Taxi and Limousine Commission,For Hire Vehicle Complaint,Car Service Company Complaint,Unlicensed/Unauthorized,Street,11430.0,JOHN F KENNEDY AIRPORT,JOHN F KENNEDY AIRPORT,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,PLACE,JAMAICA,JOHN F KENNEDY AIRPORT,NaN,In Progress,NaN,NaN,NaN,83 QUEENS,31.0,Precinct 113,4.142600e+09,QUEENS,"1,043,001","175,548",ONLINE,Unspecified,QUEENS,Car Service,NaN,"JOHN F KENNEDY AIRPORT, QUEENS (JAMAICA) ,NY, 11430",NaN,NaN,NaN,NaN,40.64832,-73.788281,POINT (-73.788281251302 40.648320486201)
8544,66465933,10/13/2025 01:28:35 PM,NaN,TLC,Taxi and Limousine Commission,For Hire Vehicle Complaint,Car Service Company Complaint,Unlicensed/Unauthorized,Street,11430.0,JOHN F KENNEDY AIRPORT,JOHN F KENNEDY AIRPORT,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,PLACE,JAMAICA,JOHN F KENNEDY AIRPORT,NaN,In Progress,NaN,NaN,NaN,83 QUEENS,31.0,Precinct 113,4.142600e+09,QUEENS,"1,043,001","175,548",ONLINE,Unspecified,QUEENS,Car Service,QUEENS,"JOHN F KENNEDY AIRPORT, QUEENS (JAMAICA) ,NY, 11430",NaN,NaN,NaN,NaN,40.64832,-73.788281,POINT (-73.788281251302 40.648320486201)
8545,66467398,10/13/2025 01:22:36 PM,NaN,TLC,Taxi and Limousine Commission,For Hire Vehicle Report,Car Service Company Report,Unlicensed/Unauthorized,NaN,11430.0,JOHN F KENNEDY AIRPORT,JOHN F KENNEDY AIRPORT,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,PLACE,JAMAICA,JOHN F KENNEDY AIRPORT,NaN,In Progress,NaN,NaN,NaN,83 QUEENS,31.0,Precinct 113,4.142600e+09,QUEENS,"1,043,001","175,548",ONLINE,Unspecified,QUEENS,NaN,NaN,"JOHN F KENNEDY AIRPORT, QUEENS (JAMAICA) ,NY, 11430",NaN,NaN,NaN,NaN,40.64832,-73.788281,POINT (-73.788281251302 40.648320486201)
8757,66442812,10/11/2025 05:20:27 AM,NaN,TLC,Taxi and Limousine Commission,For Hire Vehicle Complaint,Car Service Company Complaint,Unlicensed/Unauthorized,Street,11430.0,JOHN F KENNEDY AIRPORT,JOHN F KENNEDY AIRPORT,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,PLACE,JAMAICA,JOHN F KENNEDY AIRPORT,NaN,In Progress,NaN,NaN,NaN,83 QUEENS,31.0,Precinct 113,4.142600e+09,QUEENS,"1,043,001","175,548",ONLINE,Unspecified,QUEENS,Car Service,NaN,"JOHN F KENNEDY AIRPORT, QUEENS (JAMAICA) ,NY, 11430",NaN,NaN,NaN,NaN,40.64832,-73.788281,POINT (-73.788281251302 40.648320486201)
11449,66197819,09/18/2025 10:18:43 AM,NaN,TLC,Taxi and Limousine Commission,For Hire Vehicle Report,Car Service Company Report,Unlicensed/Unauthorized,NaN,11430.0,JFK,JFK,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,PLACE,JAMAICA,JOHN F KENNEDY AIRPORT,NaN,In Progress,NaN,NaN,NaN,83 QUEENS,31.0,Precinct 113,4.142600e+09,QUEENS,"1,043,001","175,548",PHONE,Unspecified,QUEENS,NaN,NaN,"JOHN F KENNEDY AIRPORT, QUEENS (JAMAICA) ,NY, 11430",NaN,NaN,NaN,NaN,40.64832,-73.788281,POINT (-73.788281251302 40.648320486201)
11479,66201810,09/18/2025 02:00:27 AM,NaN,TLC,Taxi and Limousine Commission,For Hire Vehicle Complaint,Car Service Company Complaint,Unlicensed/Unauthorized,Street,11430.0,JOHN F KENNEDY AIRPORT,JOHN F KENNEDY AIRPORT,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,PLACE,JAMAICA,JOHN F KENNEDY AIRPORT,NaN,In Progress,NaN,NaN,NaN,83 QUEENS,31.0,Precinct 113,4.142600e+09,QUEENS,"1,043,001","175,548",ONLINE,Unspecified,QUEENS,Car Service,QUEENS,"JOHN F KENNEDY AIRPORT, QUEENS (JAMAICA) ,NY, 11430",NaN,NaN,NaN,NaN,40.64832,-73.788281,POINT (-73.788281251302 40.648320486201)
13141,66020494,09/01/2025 11:49:05 PM,NaN,TLC,Taxi and Limousine Commission,For Hire Vehicle Complaint,Car Service Company Complaint,Unlicensed/Unauthorized,Street,11430.0,JOHN F KENNEDY AIRPORT,JOHN F KENNEDY AIRPORT,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,PLACE,JAMAICA,JOHN F KENNEDY AIRPORT,NaN,In Progress,NaN,NaN,NaN,83 QUEENS,31.0,Precinct 113,4.142600e+09,QUEENS,"1,043,001","175,548",ONLINE,Unspecified,QUEENS,Car Service,MANHATTAN,"JOHN F KENNEDY AIRPORT, QUEENS (JAMAICA) ,NY, 11430",NaN,NaN,NaN,NaN,40.64832,-73.788281,POINT (-73.788281251302 40.648320486201)
13536,65973145,08/28/2025 10:00:23 PM,NaN,TLC,Taxi and Limousine Commission,For Hire Vehicle Complaint,Car Service Company Complaint,Unlicensed/Unauthorized,Street,11430.0,JOHN F KENNEDY AIRPORT,JOHN F KENNEDY AIRPORT,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,PLACE,JAMAICA,JOHN F KENNEDY AIRPORT,NaN,In Progress,NaN,NaN,NaN,83 QUEENS,31.0,Precinct 113,4.142600e+09,QUEENS,"1,043,001","175,548",ONLINE,Unspecified,QUEENS,Car Service,NaN,"JOHN F KENNEDY AIRPORT, QUEENS (JAMAICA) ,NY, 11430",NaN,NaN,NaN,NaN,40.64832,-73.788281,POINT (-73.788281251302 40.648320486201)
13736,65961164,08/26/2025 06:20:27 PM,12/02/2025 01:59:21 PM,TLC,Taxi and Limousine Commission,For Hire Vehicle Complaint,Car Service Company Complaint,Unlicensed/Unauthorized,Street,11430.0,JFK,JFK,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,PLACE,JAMAICA,JOHN F KENNEDY AIRPORT,NaN,Closed,NaN,"Based on the information provided by the customer, the Taxi and Limousine Commission has determined that a hearing is not necessary or not possible.",12/02/2025 01:59:26 PM,83 QUEENS,31.0,Precinct 113,4.142600e+09,QUEENS,"1,043,001","175,548",PHONE,Unspecified,QUEENS,Car Service,NaN,"JOHN F KENNEDY AIRPORT, QUEENS (JAMAICA) ,NY, 11430",NaN,NaN,NaN,NaN,40.64832,-73.788281,POINT (-73.788281251302 40.648320486201)
15019,65855280,08/14/2025 06:26:32 PM,12/16/2025 10:01:32 AM,TLC,Taxi and Limousine Commission,For Hire Vehicle Complaint,Car Service Company Complaint,Unlicensed/Unauthorized,Street,11430.0,JOHN F KENNEDY AIRPORT,JOHN F KENNEDY AIRPORT,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,PLACE,JAMAICA,JOHN F KENNEDY AIRPORT,NaN,Closed,NaN,The Taxi and Limousine Commission was unable to identify the driver or car service company named in your complaint.,12/16/2025 10:01:34 AM,83 QUEENS,31.0,Precinct 113,4.142600e+09,QUEENS,"1,043,001","175,548",ONLINE,Unspecified,QUEENS,Car Service,NaN,"JOHN F KENNEDY AIRPORT, QUEENS (JAMAICA) ,NY, 11430",NaN,NaN,NaN,NaN,40.64832,-73.788281,POINT (-73.788281251302 40.648320486201)
17280,65623615,07/22/2025 12:23:45 AM,12/04/2025 07:30:15 AM,TLC,Taxi and Limousine Commission,For Hire Vehicle Complaint,Car Service Company Complaint,Unlicensed/Unauthorized,Street,11430.0,JOHN F KENNEDY AIRPORT,JOHN F KENNEDY AIRPORT,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,PLACE,JAMAICA,JOHN F KENNEDY AIRPORT,NaN,Closed,NaN,"The Taxi and Limousine Commission (TLC) called and left a message for you. They needed to confirm the details of your complaint. When you did not respond within 14 days, your complaint was closed. If you still want to pursue this complaint, you can open a new Service Request with a daytime phone number included.",12/04/2025 07:30:17 AM,83 QUEENS,31.0,Precinct 113,4.142600e+09,QUEENS,"1,043,001","175,548",ONLINE,Unspecified,QUEENS,Car Service,BROOKLYN,"JOHN F KENNEDY AIRPORT, QUEENS (JAMAICA) ,NY, 11430",NaN,NaN,NaN,NaN,40.64832,-73.788281,POINT (-73.788281251302 40.648320486201)
17419,65615718,07/20/2025 07:47:02 PM,NaN,TLC,Taxi and Limousine Commission,For Hire Vehicle Complaint,Car Service Company Complaint,Unlicensed/Unauthorized,Highway,11430.0,JOHN F KENNEDY AIRPORT,JOHN F KENNEDY AIRPORT,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,PLACE,JAMAICA,JOHN F KENNEDY AIRPORT,NaN,In Progress,NaN,NaN,NaN,83 QUEENS,31.0,Precinct 113,4.142600e+09,QUEENS,"1,043,001","175,548",ONLINE,Unspecified,QUEENS,Car Service,MANHATTAN,"JOHN F KENNEDY AIRPORT, QUEENS (JAMAICA) ,NY, 11430",Henry Hudson Pkwy/Rt 9A,North/Bronx Bound,Roadway,Dyckman St (Exit 17) - Br Toll Plaza,40.64832,-73.788281,POINT (-73.788281251302 40.648320486201)
18769,65486382,07/06/2025 08:41:07 PM,12/01/2025 03:19:46 PM,TLC,Taxi and Limousine Commission,For Hire Vehicle Complaint,Car Service Company Complaint,Unlicensed/Unauthorized,Street,11430.0,JOHN F KENNEDY AIRPORT,JOHN F KENNEDY AIRPORT,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,PLACE,JAMAICA,JOHN F KENNEDY AIRPORT,NaN,Closed,NaN,The Taxi and Limousine Commission was unable to identify the driver or car service company named in your complaint.,12/01/2025 03:19:49 PM,83 QUEENS,31.0,Precinct 113,4.142600e+09,QUEENS,"1,043,001","175,548",ONLINE,Unspecified,QUEENS,Car Service,NaN,"JOHN F KENNEDY AIRPORT, QUEENS (JAMAICA) ,NY, 11430",NaN,NaN,NaN,NaN,40.64832,-73.788281,POINT (-73.788281251302 40.648320486201)
19019,65451636,07/03/2025 07:21:17 PM,NaN,TLC,Taxi and Limousine Commission,For Hire Vehicle Complaint,Car Service Company Complaint,Unlicensed/Unauthorized,Street,11430.0,JFK,JFK,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,PLACE,JAMAICA,JOHN F KENNEDY AIRPORT,NaN,In Progress,NaN,NaN,NaN,83 QUEENS,31.0,Precinct 113,4.142600e+09,QUEENS,"1,043,001","175,548",PHONE,Unspecified,QUEENS,Car Service,QUEENS,"JOHN F KENNEDY AIRPORT, QUEENS (JAMAICA) ,NY, 11430",NaN,NaN,NaN,NaN,40.64832,-73.788281,POINT (-73.788281251302 40.648320486201)
19021,65451637,07/03/2025 07:10:17 PM,12/02/2025 01:18:32 PM,TLC,Taxi and Limousine Commission,For Hire Vehicle Complaint,Car Service Company Complaint,Unlicensed/Unauthorized,Street,11430.0,JFK,JFK,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,PLACE,JAMAICA,JOHN F KENNEDY AIRPORT,NaN,Closed,NaN,"Based on the information provided by the customer, the Taxi and Limousine Commission has determined that a hearing is not necessary or not possible.",12/02/2025 01:18:35 PM,83 QUEENS,31.0,Precinct 113,4.142600e+09,QUEENS,"1,043,001","175,548",PHONE,Unspecified,QUEENS,Car Service,NaN,"JOHN F KENNEDY AIRPORT, QUEENS (JAMAICA) ,NY, 11430",NaN,NaN,NaN,NaN,40.64832,-73.788281,POINT (-73.788281251302 40.648320486201)

In [51]:
## counting the total complaints vs. those closed bc they oculdn't track them down
complaint_jfk.count()

Unique Key                              40
Created Date                            40
Closed Date                             19
Agency                                  40
Agency Name                             40
Problem (formerly Complaint Type)       40
Problem Detail (formerly Descriptor)    40
Additional Details                      40
Location Type                           34
Incident Zip                            40
Incident Address                        40
Street Name                             40
Cross Street 1                          40
Cross Street 2                          40
Intersection Street 1                   40
Intersection Street 2                   40
Address Type                            40
City                                    40
Landmark                                40
Facility Type                            0
Status                                  40
Due Date                                 0
Resolution Description                  19
Resolution Action Updated Date          19
Community Board                         40
Council District                        40
Police Precinct                         40
BBL                                     40
Borough                                 40
X Coordinate (State Plane)              40
Y Coordinate (State Plane)              40
Open Data Channel Type                  40
Park Facility Name                      40
Park Borough                            40
Vehicle Type                            34
Taxi Company Borough                    19
Taxi Pick Up Location                   40
Bridge Highway Name                      2
Bridge Highway Direction                 2
Road Ramp                                2
Bridge Highway Segment                   2
Latitude                                40
Longitude                               40
Location                                40
dtype: int64

In [67]:
complaint_jfk

,Unique Key,Created Date,Closed Date,Agency,Agency Name,Problem (formerly Complaint Type),Problem Detail (formerly Descriptor),Additional Details,Location Type,Incident Zip,Incident Address,Street Name,Cross Street 1,Cross Street 2,Intersection Street 1,Intersection Street 2,Address Type,City,Landmark,Facility Type,Status,Due Date,Resolution Description,Resolution Action Updated Date,Community Board,Council District,Police Precinct,BBL,Borough,X Coordinate (State Plane),Y Coordinate (State Plane),Open Data Channel Type,Park Facility Name,Park Borough,Vehicle Type,Taxi Company Borough,Taxi Pick Up Location,Bridge Highway Name,Bridge Highway Direction,Road Ramp,Bridge Highway Segment,Latitude,Longitude,Location
70,67335775,12/30/2025 10:52:55 PM,NaN,TLC,Taxi and Limousine Commission,For Hire Vehicle Complaint,Car Service Company Complaint,Unlicensed/Unauthorized,Street,11430.0,JOHN F KENNEDY AIRPORT,JOHN F KENNEDY AIRPORT,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,PLACE,JAMAICA,JOHN F KENNEDY AIRPORT,NaN,In Progress,NaN,NaN,NaN,83 QUEENS,31.0,Precinct 113,4.142600e+09,QUEENS,"1,043,001","175,548",ONLINE,Unspecified,QUEENS,Car Service,NaN,"JOHN F KENNEDY AIRPORT, QUEENS (JAMAICA) ,NY, 11430",NaN,NaN,NaN,NaN,40.64832,-73.788281,POINT (-73.788281251302 40.648320486201)
173,67329354,12/29/2025 05:40:14 PM,03/11/2026 02:44:36 PM,TLC,Taxi and Limousine Commission,For Hire Vehicle Complaint,Car Service Company Complaint,Unlicensed/Unauthorized,Street,11430.0,JOHN F KENNEDY AIRPORT,JOHN F KENNEDY AIRPORT,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,PLACE,JAMAICA,JOHN F KENNEDY AIRPORT,NaN,Closed,NaN,"Based on the information provided by the customer, the Taxi and Limousine Commission has determined that a hearing is not necessary or not possible.",03/11/2026 02:44:40 PM,83 QUEENS,31.0,Precinct 113,4.142600e+09,QUEENS,"1,043,001","175,548",ONLINE,Unspecified,QUEENS,Car Service,QUEENS,"JOHN F KENNEDY AIRPORT, QUEENS (JAMAICA) ,NY, 11430",NaN,NaN,NaN,NaN,40.64832,-73.788281,POINT (-73.788281251302 40.648320486201)
568,67277487,12/23/2025 12:04:21 PM,03/11/2026 02:35:00 PM,TLC,Taxi and Limousine Commission,For Hire Vehicle Complaint,Car Service Company Complaint,Unlicensed/Unauthorized,Street,11430.0,JOHN F KENNEDY AIRPORT,JOHN F KENNEDY AIRPORT,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,PLACE,JAMAICA,JOHN F KENNEDY AIRPORT,NaN,Closed,NaN,"Based on the information provided by the customer, the Taxi and Limousine Commission has determined that a hearing is not necessary or not possible.",03/11/2026 02:35:02 PM,83 QUEENS,31.0,Precinct 113,4.142600e+09,QUEENS,"1,043,001","175,548",PHONE,Unspecified,QUEENS,Car Service,QUEENS,"JOHN F KENNEDY AIRPORT, QUEENS (JAMAICA) ,NY, 11430",NaN,NaN,NaN,NaN,40.64832,-73.788281,POINT (-73.788281251302 40.648320486201)
616,67273967,12/22/2025 07:27:58 PM,NaN,TLC,Taxi and Limousine Commission,For Hire Vehicle Complaint,Car Service Company Complaint,Unlicensed/Unauthorized,Highway,11430.0,JOHN F KENNEDY AIRPORT,JOHN F KENNEDY AIRPORT,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,PLACE,JAMAICA,JOHN F KENNEDY AIRPORT,NaN,In Progress,NaN,NaN,NaN,83 QUEENS,31.0,Precinct 113,4.142600e+09,QUEENS,"1,043,001","175,548",ONLINE,Unspecified,QUEENS,Car Service,NaN,"JOHN F KENNEDY AIRPORT, QUEENS (JAMAICA) ,NY, 11430",Van Wyck Expwy,North/Bronx Bound,Ramp,Jamaica Ave Hillside Ave (Exit 6),40.64832,-73.788281,POINT (-73.788281251302 40.648320486201)
774,67254238,12/20/2025 08:24:14 PM,NaN,TLC,Taxi and Limousine Commission,For Hire Vehicle Report,Car Service Company Report,Unlicensed/Unauthorized,NaN,11430.0,JOHN F KENNEDY AIRPORT,JOHN F KENNEDY AIRPORT,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,PLACE,JAMAICA,JOHN F KENNEDY AIRPORT,NaN,In Progress,NaN,NaN,NaN,83 QUEENS,31.0,Precinct 113,4.142600e+09,QUEENS,"1,043,001","175,548",ONLINE,Unspecified,QUEENS,NaN,NaN,"JOHN F KENNEDY AIRPORT, QUEENS (JAMAICA) ,NY, 11430",NaN,NaN,NaN,NaN,40.64832,-73.788281,POINT (-73.788281251302 40.648320486201)
1445,67199698,12/15/2025 05:05:42 AM,NaN,TLC,Taxi and Limousine Commission,For Hire Vehicle Report,Car Service Company Report,Unlicensed/Unauthorized,NaN,11430.0,JOHN F KENNEDY AIRPORT,JOHN F KENNEDY AIRPORT,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,PLACE,JAMAICA,JOHN F KENNEDY AIRPORT,NaN,In Progress,NaN,NaN,NaN,83 QUEENS,31.0,Precinct 113,4.142600e+09,QUEENS,"1,043,001","175,548",ONLINE,Unspecified,QUEENS,NaN,NaN,"JOHN F KENNEDY AIRPORT, QUEENS (JAMAICA) ,NY, 11430",NaN,NaN,NaN,NaN,40.64832,-73.788281,POINT (-73.788281251302 40.648320486201)
2254,67089128,12/07/2025 11:25:30 PM,NaN,TLC,Taxi and Limousine Commission,For Hire Vehicle Report,Car Service Company Report,Unlicensed/Unauthorized,NaN,11430.0,JOHN F KENNEDY AIRPORT,JOHN F KENNEDY AIRPORT,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,PLACE,JAMAICA,JOHN F KENNEDY AIRPORT,NaN,In Progress,NaN,NaN,NaN,83 QUEENS,31.0,Precinct 113,4.142600e+09,QUEENS,"1,043,001","175,548",PHONE,Unspecified,QUEENS,NaN,NaN,"JOHN F KENNEDY AIRPORT, QUEENS (JAMAICA) ,NY, 11430",NaN,NaN,NaN,NaN,40.64832,-73.788281,POINT (-73.788281251302 40.648320486201)
2998,67012871,12/01/2025 10:05:41 PM,NaN,TLC,Taxi and Limousine Commission,For Hire Vehicle Complaint,Car Service Company Complaint,Unlicensed/Unauthorized,Street,11430.0,JOHN F KENNEDY AIRPORT,JOHN F KENNEDY AIRPORT,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,PLACE,JAMAICA,JOHN F KENNEDY AIRPORT,NaN,In Progress,NaN,NaN,NaN,83 QUEENS,31.0,Precinct 113,4.142600e+09,QUEENS,"1,043,001","175,548",ONLINE,Unspecified,QUEENS,Car Service,MANHATTAN,"JOHN F KENNEDY AIRPORT, QUEENS (JAMAICA) ,NY, 11430",NaN,NaN,NaN,NaN,40.64832,-73.788281,POINT (-73.788281251302 40.648320486201)
3085,67001665,12/01/2025 12:10:04 AM,NaN,TLC,Taxi and Limousine Commission,For Hire Vehicle Complaint,Car Service Company Complaint,Unlicensed/Unauthorized,Street,11430.0,JOHN F KENNEDY AIRPORT,JOHN F KENNEDY AIRPORT,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,PLACE,JAMAICA,JOHN F KENNEDY AIRPORT,NaN,In Progress,NaN,NaN,NaN,83 QUEENS,31.0,Precinct 113,4.142600e+09,QUEENS,"1,043,001","175,548",ONLINE,Unspecified,QUEENS,Car Service,QUEENS,"JOHN F KENNEDY AIRPORT, QUEENS (JAMAICA) ,NY, 11430",NaN,NaN,NaN,NaN,40.64832,-73.788281,POINT (-73.788281251302 40.648320486201)
3484,66953982,11/25/2025 11:06:30 PM,NaN,TLC,Taxi and Limousine Commission,For Hire Vehicle Report,Car Service Company Report,Unlicensed/Unauthorized,NaN,11430.0,JOHN F KENNEDY AIRPORT,JOHN F KENNEDY AIRPORT,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,PLACE,JAMAICA,JOHN F KENNEDY AIRPORT,NaN,In Progress,NaN,NaN,NaN,83 QUEENS,31.0,Precinct 113,4.142600e+09,QUEENS,"1,043,001","175,548",ONLINE,Unspecified,QUEENS,NaN,NaN,"JOHN F KENNEDY AIRPORT, QUEENS (JAMAICA) ,NY, 11430",NaN,NaN,NaN,NaN,40.64832,-73.788281,POINT (-73.788281251302 40.648320486201)
3647,66940679,11/24/2025 01:49:37 PM,NaN,TLC,Taxi and Limousine Commission,For Hire Vehicle Complaint,Car Service Company Complaint,Unlicensed/Unauthorized,Street,11430.0,JOHN F KENNEDY AIRPORT,JOHN F KENNEDY AIRPORT,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,PLACE,JAMAICA,JOHN F KENNEDY AIRPORT,NaN,In Progress,NaN,NaN,NaN,83 QUEENS,31.0,Precinct 113,4.142600e+09,QUEENS,"1,043,001","175,548",PHONE,Unspecified,QUEENS,Car Service,QUEENS,"JOHN F KENNEDY AIRPORT, QUEENS (JAMAICA) ,NY, 11430",NaN,NaN,NaN,NaN,40.64832,-73.788281,POINT (-73.788281251302 40.648320486201)
5020,66815666,11/12/2025 09:12:02 AM,NaN,TLC,Taxi and Limousine Commission,For Hire Vehicle Complaint,Car Service Company Complaint,Unlicensed/Unauthorized,Street,11430.0,JOHN F KENNEDY AIRPORT,JOHN F KENNEDY AIRPORT,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,PLACE,JAMAICA,JOHN F KENNEDY AIRPORT,NaN,In Progress,NaN,NaN,NaN,83 QUEENS,31.0,Precinct 113,4.142600e+09,QUEENS,"1,043,001","175,548",ONLINE,Unspecified,QUEENS,Car Service,NaN,"JOHN F KENNEDY AIRPORT, QUEENS (JAMAICA) ,NY, 11430",NaN,NaN,NaN,NaN,40.64832,-73.788281,POINT (-73.788281251302 40.648320486201)
5034,66817439,11/12/2025 07:51:58 AM,NaN,TLC,Taxi and Limousine Commission,For Hire Vehicle Complaint,Car Service Company Complaint,Unlicensed/Unauthorized,Street,11430.0,JOHN F KENNEDY AIRPORT,JOHN F KENNEDY AIRPORT,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,PLACE,JAMAICA,JOHN F KENNEDY AIRPORT,NaN,In Progress,NaN,NaN,NaN,83 QUEENS,31.0,Precinct 113,4.142600e+09,QUEENS,"1,043,001","175,548",ONLINE,Unspecified,QUEENS,Car Service,BROOKLYN,"JOHN F KENNEDY AIRPORT, QUEENS (JAMAICA) ,NY, 11430",NaN,NaN,NaN,NaN,40.64832,-73.788281,POINT (-73.788281251302 40.648320486201)
5279,66778128,11/10/2025 12:50:49 AM,03/11/2026 10:07:04 AM,TLC,Taxi and Limousine Commission,For Hire Vehicle Complaint,Car Service Company Complaint,Unlicensed/Unauthorized,Street,11430.0,JOHN F KENNEDY AIRPORT,JOHN F KENNEDY AIRPORT,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,PLACE,JAMAICA,JOHN F KENNEDY AIRPORT,NaN,Closed,NaN,"Based on the information provided by the customer, the Taxi and Limousine Commission has determined that a hearing is not necessary or not possible.",03/11/2026 10:07:06 AM,83 QUEENS,31.0,Precinct 113,4.142600e+09,QUEENS,"1,043,001","175,548",ONLINE,Unspecified,QUEENS,Car Service,NaN,"JOHN F KENNEDY AIRPORT, QUEENS (JAMAICA) ,NY, 11430",NaN,NaN,NaN,NaN,40.64832,-73.788281,POINT (-73.788281251302 40.648320486201)
6079,66690152,11/01/2025 10:01:14 PM,NaN,TLC,Taxi and Limousine Commission,For Hire Vehicle Complaint,Car Service Company Complaint,Unlicensed/Unauthorized,Street,11430.0,JOHN F KENNEDY AIRPORT,JOHN F KENNEDY AIRPORT,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,PLACE,JAMAICA,JOHN F KENNEDY AIRPORT,NaN,In Progress,NaN,NaN,NaN,83 QUEENS,31.0,Precinct 113,4.142600e+09,QUEENS,"1,043,001","175,548",ONLINE,Unspecified,QUEENS,Car Service,NaN,"JOHN F KENNEDY AIRPORT, QUEENS (JAMAICA) ,NY, 11430",NaN,NaN,NaN,NaN,40.64832,-73.788281,POINT (-73.788281251302 40.648320486201)
8544,66465933,10/13/2025 01:28:35 PM,NaN,TLC,Taxi and Limousine Commission,For Hire Vehicle Complaint,Car Service Company Complaint,Unlicensed/Unauthorized,Street,11430.0,JOHN F KENNEDY AIRPORT,JOHN F KENNEDY AIRPORT,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,PLACE,JAMAICA,JOHN F KENNEDY AIRPORT,NaN,In Progress,NaN,NaN,NaN,83 QUEENS,31.0,Precinct 113,4.142600e+09,QUEENS,"1,043,001","175,548",ONLINE,Unspecified,QUEENS,Car Service,QUEENS,"JOHN F KENNEDY AIRPORT, QUEENS (JAMAICA) ,NY, 11430",NaN,NaN,NaN,NaN,40.64832,-73.788281,POINT (-73.788281251302 40.648320486201)
8545,66467398,10/13/2025 01:22:36 PM,NaN,TLC,Taxi and Limousine Commission,For Hire Vehicle Report,Car Service Company Report,Unlicensed/Unauthorized,NaN,11430.0,JOHN F KENNEDY AIRPORT,JOHN F KENNEDY AIRPORT,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,PLACE,JAMAICA,JOHN F KENNEDY AIRPORT,NaN,In Progress,NaN,NaN,NaN,83 QUEENS,31.0,Precinct 113,4.142600e+09,QUEENS,"1,043,001","175,548",ONLINE,Unspecified,QUEENS,NaN,NaN,"JOHN F KENNEDY AIRPORT, QUEENS (JAMAICA) ,NY, 11430",NaN,NaN,NaN,NaN,40.64832,-73.788281,POINT (-73.788281251302 40.648320486201)
8757,66442812,10/11/2025 05:20:27 AM,NaN,TLC,Taxi and Limousine Commission,For Hire Vehicle Complaint,Car Service Company Complaint,Unlicensed/Unauthorized,Street,11430.0,JOHN F KENNEDY AIRPORT,JOHN F KENNEDY AIRPORT,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,PLACE,JAMAICA,JOHN F KENNEDY AIRPORT,NaN,In Progress,NaN,NaN,NaN,83 QUEENS,31.0,Precinct 113,4.142600e+09,QUEENS,"1,043,001","175,548",ONLINE,Unspecified,QUEENS,Car Service,NaN,"JOHN F KENNEDY AIRPORT, QUEENS (JAMAICA) ,NY, 11430",NaN,NaN,NaN,NaN,40.64832,-73.788281,POINT (-73.788281251302 40.648320486201)
11449,66197819,09/18/2025 10:18:43 AM,NaN,TLC,Taxi and Limousine Commission,For Hire Vehicle Report,Car Service Company Report,Unlicensed/Unauthorized,NaN,11430.0,JFK,JFK,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,PLACE,JAMAICA,JOHN F KENNEDY AIRPORT,NaN,In Progress,NaN,NaN,NaN,83 QUEENS,31.0,Precinct 113,4.142600e+09,QUEENS,"1,043,001","175,548",PHONE,Unspecified,QUEENS,NaN,NaN,"JOHN F KENNEDY AIRPORT, QUEENS (JAMAICA) ,NY, 11430",NaN,NaN,NaN,NaN,40.64832,-73.788281,POINT (-73.788281251302 40.648320486201)
11479,66201810,09/18/2025 02:00:27 AM,NaN,TLC,Taxi and Limousine Commission,For Hire Vehicle Complaint,Car Service Company Complaint,Unlicensed/Unauthorized,Street,11430.0,JOHN F KENNEDY AIRPORT,JOHN F KENNEDY AIRPORT,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,PLACE,JAMAICA,JOHN F KENNEDY AIRPORT,NaN,In Progress,NaN,NaN,NaN,83 QUEENS,31.0,Precinct 113,4.142600e+09,QUEENS,"1,043,001","175,548",ONLINE,Unspecified,QUEENS,Car Service,QUEENS,"JOHN F KENNEDY AIRPORT, QUEENS (JAMAICA) ,NY, 11430",NaN,NaN,NaN,NaN,40.64832,-73.788281,POINT (-73.788281251302 40.648320486201)
13141,66020494,09/01/2025 11:49:05 PM,NaN,TLC,Taxi and Limousine Commission,For Hire Vehicle Complaint,Car Service Company Complaint,Unlicensed/Unauthorized,Street,11430.0,JOHN F KENNEDY AIRPORT,JOHN F KENNEDY AIRPORT,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,PLACE,JAMAICA,JOHN F KENNEDY AIRPORT,NaN,In Progress,NaN,NaN,NaN,83 QUEENS,31.0,Precinct 113,4.142600e+09,QUEENS,"1,043,001","175,548",ONLINE,Unspecified,QUEENS,Car Service,MANHATTAN,"JOHN F KENNEDY AIRPORT, QUEENS (JAMAICA) ,NY, 11430",NaN,NaN,NaN,NaN,40.64832,-73.788281,POINT (-73.788281251302 40.648320486201)
13536,65973145,08/28/2025 10:00:23 PM,NaN,TLC,Taxi and Limousine Commission,For Hire Vehicle Complaint,Car Service Company Complaint,Unlicensed/Unauthorized,Street,11430.0,JOHN F KENNEDY AIRPORT,JOHN F KENNEDY AIRPORT,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,PLACE,JAMAICA,JOHN F KENNEDY AIRPORT,NaN,In Progress,NaN,NaN,NaN,83 QUEENS,31.0,Precinct 113,4.142600e+09,QUEENS,"1,043,001","175,548",ONLINE,Unspecified,QUEENS,Car Service,NaN,"JOHN F KENNEDY AIRPORT, QUEENS (JAMAICA) ,NY, 11430",NaN,NaN,NaN,NaN,40.64832,-73.788281,POINT (-73.788281251302 40.648320486201)
13736,65961164,08/26/2025 06:20:27 PM,12/02/2025 01:59:21 PM,TLC,Taxi and Limousine Commission,For Hire Vehicle Complaint,Car Service Company Complaint,Unlicensed/Unauthorized,Street,11430.0,JFK,JFK,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,PLACE,JAMAICA,JOHN F KENNEDY AIRPORT,NaN,Closed,NaN,"Based on the information provided by the customer, the Taxi and Limousine Commission has determined that a hearing is not necessary or not possible.",12/02/2025 01:59:26 PM,83 QUEENS,31.0,Precinct 113,4.142600e+09,QUEENS,"1,043,001","175,548",PHONE,Unspecified,QUEENS,Car Service,NaN,"JOHN F KENNEDY AIRPORT, QUEENS (JAMAICA) ,NY, 11430",NaN,NaN,NaN,NaN,40.64832,-73.788281,POINT (-73.788281251302 40.648320486201)
15019,65855280,08/14/2025 06:26:32 PM,12/16/2025 10:01:32 AM,TLC,Taxi and Limousine Commission,For Hire Vehicle Complaint,Car Service Company Complaint,Unlicensed/Unauthorized,Street,11430.0,JOHN F KENNEDY AIRPORT,JOHN F KENNEDY AIRPORT,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,PLACE,JAMAICA,JOHN F KENNEDY AIRPORT,NaN,Closed,NaN,The Taxi and Limousine Commission was unable to identify the driver or car service company named in your complaint.,12/16/2025 10:01:34 AM,83 QUEENS,31.0,Precinct 113,4.142600e+09,QUEENS,"1,043,001","175,548",ONLINE,Unspecified,QUEENS,Car Service,NaN,"JOHN F KENNEDY AIRPORT, QUEENS (JAMAICA) ,NY, 11430",NaN,NaN,NaN,NaN,40.64832,-73.788281,POINT (-73.788281251302 40.648320486201)
17280,65623615,07/22/2025 12:23:45 AM,12/04/2025 07:30:15 AM,TLC,Taxi and Limousine Commission,For Hire Vehicle Complaint,Car Service Company Complaint,Unlicensed/Unauthorized,Street,11430.0,JOHN F KENNEDY AIRPORT,JOHN F KENNEDY AIRPORT,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,PLACE,JAMAICA,JOHN F KENNEDY AIRPORT,NaN,Closed,NaN,"The Taxi and Limousine Commission (TLC) called and left a message for you. They needed to confirm the details of your complaint. When you did not respond within 14 days, your complaint was closed. If you still want to pursue this complaint, you can open a new Service Request with a daytime phone number included.",12/04/2025 07:30:17 AM,83 QUEENS,31.0,Precinct 113,4.142600e+09,QUEENS,"1,043,001","175,548",ONLINE,Unspecified,QUEENS,Car Service,BROOKLYN,"JOHN F KENNEDY AIRPORT, QUEENS (JAMAICA) ,NY, 11430",NaN,NaN,NaN,NaN,40.64832,-73.788281,POINT (-73.788281251302 40.648320486201)
17419,65615718,07/20/2025 07:47:02 PM,NaN,TLC,Taxi and Limousine Commission,For Hire Vehicle Complaint,Car Service Company Complaint,Unlicensed/Unauthorized,Highway,11430.0,JOHN F KENNEDY AIRPORT,JOHN F KENNEDY AIRPORT,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,PLACE,JAMAICA,JOHN F KENNEDY AIRPORT,NaN,In Progress,NaN,NaN,NaN,83 QUEENS,31.0,Precinct 113,4.142600e+09,QUEENS,"1,043,001","175,548",ONLINE,Unspecified,QUEENS,Car Service,MANHATTAN,"JOHN F KENNEDY AIRPORT, QUEENS (JAMAICA) ,NY, 11430",Henry Hudson Pkwy/Rt 9A,North/Bronx Bound,Roadway,Dyckman St (Exit 17) - Br Toll Plaza,40.64832,-73.788281,POINT (-73.788281251302 40.648320486201)
18769,65486382,07/06/2025 08:41:07 PM,12/01/2025 03:19:46 PM,TLC,Taxi and Limousine Commission,For Hire Vehicle Complaint,Car Service Company Complaint,Unlicensed/Unauthorized,Street,11430.0,JOHN F KENNEDY AIRPORT,JOHN F KENNEDY AIRPORT,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,PLACE,JAMAICA,JOHN F KENNEDY AIRPORT,NaN,Closed,NaN,The Taxi and Limousine Commission was unable to identify the driver or car service company named in your complaint.,12/01/2025 03:19:49 PM,83 QUEENS,31.0,Precinct 113,4.142600e+09,QUEENS,"1,043,001","175,548",ONLINE,Unspecified,QUEENS,Car Service,NaN,"JOHN F KENNEDY AIRPORT, QUEENS (JAMAICA) ,NY, 11430",NaN,NaN,NaN,NaN,40.64832,-73.788281,POINT (-73.788281251302 40.648320486201)
19019,65451636,07/03/2025 07:21:17 PM,NaN,TLC,Taxi and Limousine Commission,For Hire Vehicle Complaint,Car Service Company Complaint,Unlicensed/Unauthorized,Street,11430.0,JFK,JFK,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,PLACE,JAMAICA,JOHN F KENNEDY AIRPORT,NaN,In Progress,NaN,NaN,NaN,83 QUEENS,31.0,Precinct 113,4.142600e+09,QUEENS,"1,043,001","175,548",PHONE,Unspecified,QUEENS,Car Service,QUEENS,"JOHN F KENNEDY AIRPORT, QUEENS (JAMAICA) ,NY, 11430",NaN,NaN,NaN,NaN,40.64832,-73.788281,POINT (-73.788281251302 40.648320486201)
19021,65451637,07/03/2025 07:10:17 PM,12/02/2025 01:18:32 PM,TLC,Taxi and Limousine Commission,For Hire Vehicle Complaint,Car Service Company Complaint,Unlicensed/Unauthorized,Street,11430.0,JFK,JFK,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,BEND,AIRTRAIN-HOWARD BCH/JAMAICA LINE,PLACE,JAMAICA,JOHN F KENNEDY AIRPORT,NaN,Closed,NaN,"Based on the information provided by the customer, the Taxi and Limousine Commission has determined that a hearing is not necessary or not possible.",12/02/2025 01:18:35 PM,83 QUEENS,31.0,Precinct 113,4.142600e+09,QUEENS,"1,043,001","175,548",PHONE,Unspecified,QUEENS,Car Service,NaN,"JOHN F KENNEDY AIRPORT, QUEENS (JAMAICA) ,NY, 11430",NaN,NaN,NaN,NaN,40.64832,-73.788281,POINT (-73.788281251302 40.648320486201)

In [44]:
## counting the total complaints vs. those closed bc they oculdn't track them down
complaint_jfk.query("`Status` == 'Closed'").count()

Unique Key                              19
Created Date                            19
Closed Date                             19
Agency                                  19
Agency Name                             19
Problem (formerly Complaint Type)       19
Problem Detail (formerly Descriptor)    19
Additional Details                      19
Location Type                           19
Incident Zip                            19
Incident Address                        19
Street Name                             19
Cross Street 1                          19
Cross Street 2                          19
Intersection Street 1                   19
Intersection Street 2                   19
Address Type                            19
City                                    19
Landmark                                19
Facility Type                            0
Status                                  19
Due Date                                 0
Resolution Description                  19
Resolution Action Updated Date          19
Community Board                         19
Council District                        19
Police Precinct                         19
BBL                                     19
Borough                                 19
X Coordinate (State Plane)              19
Y Coordinate (State Plane)              19
Open Data Channel Type                  19
Park Facility Name                      19
Park Borough                            19
Vehicle Type                            19
Taxi Company Borough                    10
Taxi Pick Up Location                   19
Bridge Highway Name                      0
Bridge Highway Direction                 0
Road Ramp                                0
Bridge Highway Segment                   0
Latitude                                19
Longitude                               19
Location                                19
dtype: int64

In [52]:
## There are 40 unlicensed complaints that have the same zip code as JFK

In [63]:
## now let's do the same for LGA

complaint_lga=unlicensed_complaint.query("`Incident Zip` == 11369")
complaint_lga.count()

Unique Key                              10
Created Date                            10
Closed Date                              3
Agency                                  10
Agency Name                             10
Problem (formerly Complaint Type)       10
Problem Detail (formerly Descriptor)    10
Additional Details                      10
Location Type                            8
Incident Zip                            10
Incident Address                        10
Street Name                             10
Cross Street 1                          10
Cross Street 2                          10
Intersection Street 1                   10
Intersection Street 2                   10
Address Type                            10
City                                    10
Landmark                                10
Facility Type                            0
Status                                  10
Due Date                                 0
Resolution Description                   3
Resolution Action Updated Date           3
Community Board                         10
Council District                        10
Police Precinct                         10
BBL                                     10
Borough                                 10
X Coordinate (State Plane)              10
Y Coordinate (State Plane)              10
Open Data Channel Type                  10
Park Facility Name                      10
Park Borough                            10
Vehicle Type                             8
Taxi Company Borough                     7
Taxi Pick Up Location                   10
Bridge Highway Name                      0
Bridge Highway Direction                 0
Road Ramp                                0
Bridge Highway Segment                   0
Latitude                                10
Longitude                               10
Location                                10
dtype: int64

In [66]:
complaint_lga.query("`Status` == 'Closed'").count()

Unique Key                              3
Created Date                            3
Closed Date                             3
Agency                                  3
Agency Name                             3
Problem (formerly Complaint Type)       3
Problem Detail (formerly Descriptor)    3
Additional Details                      3
Location Type                           3
Incident Zip                            3
Incident Address                        3
Street Name                             3
Cross Street 1                          3
Cross Street 2                          3
Intersection Street 1                   3
Intersection Street 2                   3
Address Type                            3
City                                    3
Landmark                                3
Facility Type                           0
Status                                  3
Due Date                                0
Resolution Description                  3
Resolution Action Updated Date          3
Community Board                         3
Council District                        3
Police Precinct                         3
BBL                                     3
Borough                                 3
X Coordinate (State Plane)              3
Y Coordinate (State Plane)              3
Open Data Channel Type                  3
Park Facility Name                      3
Park Borough                            3
Vehicle Type                            3
Taxi Company Borough                    2
Taxi Pick Up Location                   3
Bridge Highway Name                     0
Bridge Highway Direction                0
Road Ramp                               0
Bridge Highway Segment                  0
Latitude                                3
Longitude                               3
Location                                3
dtype: int64

In [6]:
## ok... how many happened in queens and/or at an airport? 

taxi_df["Park Borough"].unique()

<StringArray>
['MANHATTAN', 'QUEENS', 'BRONX', 'BROOKLYN', 'Unspecified', 'STATEN ISLAND']
Length: 6, dtype: str

In [7]:
taxi_df["Park Borough"].value_counts()

Park Borough
MANHATTAN        20767
QUEENS            8232
BROOKLYN          5102
BRONX             1252
Unspecified        739
STATEN ISLAND      133
Name: count, dtype: int64

In [8]:
## counting citations at JFK

count = taxi_df['Taxi Pick Up Location'].str.contains('KENNEDY', na=False).sum()
print(f"KENNEDY count: {count}")

KENNEDY count: 3915

In [9]:
## counting mentions of LGA

la_guardia_count = taxi_df['Taxi Pick Up Location'].str.contains('LA GUARDIA', na=False).sum()
laguardia_count = taxi_df['Taxi Pick Up Location'].str.contains('LAGUARDIA', na=False).sum()
total = la_guardia_count + laguardia_count
print(f"LA GUARDIA: {la_guardia_count}")
print(f"LaGuardia: {laguardia_count}")
print(f"Total: {total}")

LA GUARDIA: 1737
LaGuardia: 14
Total: 1751

## Replicating Excel Analysis

In [6]:
## citations across years

jfk_25 = 1732
jfk_24 = 972
jfk_23 = 1512
jfk_22 = 1400
jfk_21 = 511
jfk_20 = 387
jfk_19 = 950

lga_25 = 395
lga_24 = 444
lga_23 = 347
lga_22=531
lga_21 = 257
lga_20 = 241
lga_19 = 618

In [2]:
cite_25={"JFK":1732, "LGA":395, "Manhattan":406, "Bronx":202,"Brooklyn":554, "Other Queens":546, "Staten Island":5}
cite_24={"JFK":972, "LGA":444, "Manhattan":242, "Bronx":101,"Brooklyn":268, "Other Queens":478, "Staten Island":4}
cite_23={"JFK":1512, "LGA":347, "Manhattan":228, "Bronx":162,"Brooklyn":286, "Other Queens":391, "Staten Island":7}
cite_22={"JFK":1400, "LGA":531, "Manhattan":198, "Bronx":194,"Brooklyn":194, "Other Queens":421, "Staten Island":10}
cite_21={"JFK":511, "LGA":257, "Manhattan":252, "Bronx":271,"Brooklyn":244, "Other Queens":312, "Staten Island":13}
cite_20={"JFK":387, "LGA":241, "Manhattan":123, "Bronx":163,"Brooklyn":589, "Other Queens":186, "Staten Island":0}
cite_19={"JFK":950, "LGA":618, "Manhattan":447, "Bronx":480,"Brooklyn":1709, "Other Queens":1236, "Staten Island":5}

In [4]:
cite_25

{'JFK': 1732,
 'LGA': 395,
 'Manhattan': 406,
 'Bronx': 202,
 'Brooklyn': 554,
 'Other Queens': 546,
 'Staten Island': 5}

In [10]:
## calculating rate of change in citations at JFK from 2024 to 2025

(jfk_25-jfk_24)/(jfk_24)*100

78.18930041152264

In [11]:
## calculating rate of change in citations at LGA from 2024 to 2025

(lga_25-lga_24)/(lga_24)*100

-11.036036036036036